title: "Gabriel – ePortfolio"
description: "Cybersecurity | Networking | Cloud | DevSecOps"
url: "https://gabrielnetsec.github.io"
baseurl: ""
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "air"  # Puedes probar también 'dark', 'neon', etc.
